version: 3.0.{build}.0
build_cloud: WIN-LKR467JS4GL
image: Windows
environment:
  DmfRootPath: C:\projects\DMF
  DOMITO_INC_PATH: C:\projects\Domito\include
  DOMITO_LIB_PATH: C:\projects\Domito\lib
platform:
- x64
- ARM64
configuration:
- Release
skip_commits:
  files:
    - '**/*.md'
install:
#- cmd: |
#    cd "C:\Tools\vcpkg"
#    git pull > NUL
#    .\bootstrap-vcpkg.bat > NUL
#    cd %appveyor_build_folder%
- cmd: git submodule -q update --init
- cmd: git clone -q https://github.com/microsoft/DMF.git C:\projects\DMF 2> nul || set ERRORLEVEL=0
- cmd: |
    cd "C:\projects\DMF"
    git pull > NUL
    cd %appveyor_build_folder%
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
before_build:
- cmd: vcpkg integrate install
- cmd: vcpkg update
- cmd: vcpkg install hidapi:x86-windows-static hidapi:x64-windows-static
- nuget restore
- cmd: vpatch.exe --stamp-version "%APPVEYOR_BUILD_VERSION%" --target-file ".\sys\dshidmini.vcxproj" --vcxproj.inf-time-stamp
- cmd: vpatch.exe --stamp-version "%APPVEYOR_BUILD_VERSION%" --target-file ".\sys\dshidmini.rc" --resource.file-version --resource.product-version
- cmd: vpatch.exe --stamp-version "%APPVEYOR_BUILD_VERSION%" --target-file ".\XInputBridge\XInputBridge.rc" --resource.file-version --resource.product-version
build_script:
- cmd: .\build.cmd
after_build:
- cmd: makecab.exe /f .\DsHidMini_%PLATFORM%.ddf
artifacts:
- path: 'disk1\*.cab'
- path: 'bin**\$(APPVEYOR_PROJECT_NAME)\*.inf'
- path: 'bin**\$(APPVEYOR_PROJECT_NAME)\*.cat'
- path: 'bin**\$(APPVEYOR_PROJECT_NAME)\*.dll'
- path: 'bin**\*.pdb'
- path: 'bin**\*.dll'
- path: 'bin\*.exe'
deploy:
- provider: Environment
  name: BUILDBOT
  on:
    appveyor_repo_tag: true
